#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 22 19:01:50 2022

@author: Sriramdayal
"""

import os
os.system("sudo apt update -y;sudo apt install neofetch;neofetch;")
os.system("git clone https://github.com/LionSec/katoolin.git ;cp katoolin/katoolin.py /usr/bin/katoolin;chmod +x /usr/bin/katoolin;sudo katoolin")

